### ISSUE TITLE
zdict crashes when querying ``style``

### ISSUE THREAD

**Issue by pi314** [zdict/zdict#100]
```
Traceback (most recent call last):
  File "/usr/home/pi314/.venv/bin/zdict", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/usr/home/pi314/bin/.repo/zdict/scripts/zdict", line 4, in <module>
    zdict.main()
  File "/usr/home/pi314/bin/.repo/zdict/zdict/zdict.py", line 310, in main
    execute_zdict(args)
  File "/usr/home/pi314/bin/.repo/zdict/zdict/zdict.py", line 292, in execute_zdict
    normal_mode(args)
  File "/usr/home/pi314/bin/.repo/zdict/zdict/zdict.py", line 202, in normal_mode
    zdict.lookup(word)
  File "/usr/home/pi314/bin/.repo/zdict/zdict/dictionary.py", line 131, in lookup
    record = self.query(word)
  File "/usr/home/pi314/bin/.repo/zdict/zdict/dictionaries/yahoo.py", line 118, in query
    tag for tag in item.find_all('span')
  File "/usr/home/pi314/bin/.repo/zdict/zdict/dictionaries/yahoo.py", line 119, in <genexpr>
    if 'line-height: 17px;' not in tag['style']
  File "/usr/home/pi314/.venv/lib/python3.4/site-packages/bs4/element.py", line 958, in __getitem__
    return self.attrs[key]
KeyError: 'style'
```

**Comment by pi314** [comment]
fixed by 9473b4f
