### ISSUE TITLE
Interactive mode failed to start with peewee >= 2.8.7

### ISSUE THREAD

**Issue by iblis17** [zdict/zdict#119]
```
└─[iblis@kaladbolg]% z
Traceback (most recent call last):
  File "/home/iblis/venv/py36/bin/zdict", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/iblis/git/zdict/scripts/zdict", line 4, in <module>
    zdict.main()
  File "/home/iblis/git/zdict/zdict/zdict.py", line 310, in main
    execute_zdict(args)
  File "/home/iblis/git/zdict/zdict/zdict.py", line 294, in execute_zdict
    interactive_mode(args)
  File "/home/iblis/git/zdict/zdict/zdict.py", line 267, in interactive_mode
    zdict = MetaInteractivePrompt(args)
  File "/home/iblis/git/zdict/zdict/zdict.py", line 224, in __init__
    dictionary_map[d](self.args) for d in self.args.dict                                                        File "/home/iblis/git/zdict/zdict/zdict.py", line 224, in <genexpr>
    dictionary_map[d](self.args) for d in self.args.dict
  File "/home/iblis/git/zdict/zdict/dictionary.py", line 23, in __init__
    self.db.connect()
  File "/home/iblis/venv/py36/lib/python3.6/site-packages/peewee.py", line 3650, in connect
    raise OperationalError('Connection already open')
peewee.OperationalError: Connection already open
Exception ignored in: <bound method MetaInteractivePrompt.__del__ of <zdict.zdict.MetaInteractivePrompt object at 0x7f736ebc2278>>
Traceback (most recent call last):
  File "/home/iblis/git/zdict/zdict/zdict.py", line 237, in __del__                                               
del self.dicts
AttributeError: dicts
```
It still works fine on peewee 2.8.5.

**Comment by wdv4758h** [comment]
What a sad news 😭

**Comment by pi314** [comment]
ಠ_ಠ

**Comment by M157q** [comment]
Welcome to the world of Open Source.

**Comment by wdv4758h** [comment]
Maybe I can fix this in the afternoon.
