### ISSUE TITLE
pip 20.1 changed something related to `parse_requirements`

### ISSUE THREAD

**Issue by M157q** [zdict/zdict#418]
https://travis-ci.org/github/zdict/zdict/builds/687708125

```
$ pip install .
Processing /Users/travis/build/zdict/zdict
    ERROR: Command errored out with exit status 1:
     command: /Users/travis/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/travis/build/zdict/zdict/setup.py'"'"'; __file__='"'"'/Users/travis/build/zdict/zdict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/pip-pip-egg-info-60zv2jj6
         cwd: /Users/travis/build/zdict/zdict/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/travis/build/zdict/zdict/setup.py", line 66, in <module>
        install_requires = [str(ir.req) for ir in install_requirements]
      File "/Users/travis/build/zdict/zdict/setup.py", line 66, in <listcomp>
        install_requires = [str(ir.req) for ir in install_requirements]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command "pip install ." failed and exited with 1 during .
```

**Comment by M157q** [comment]
ref: https://github.com/pypa/pip/issues/8188

**Comment by M157q** [comment]
pip 20.1 moved `parse_requirements()` to `pip._vendor.pkg_resources`
ref: https://github.com/pypa/pip/blob/1e67c3cc201c3eaf7ac6927954729a01e4c28e45/src/pip/_internal/req/constructors.py#L18
