### ISSUE TITLE
yahoo dict crashes when querying "運作"

### ISSUE THREAD

**Issue by pi314** [zdict/zdict#51]
```
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/zdict", line 4, in <module>
    zdict.main()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zdict/zdict.py", line 207, in main
    execute_zdict()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zdict/zdict.py", line 191, in execute_zdict
    normal_mode()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zdict/zdict.py", line 152, in normal_mode
    zdict.lookup(word, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zdict/dictionary.py", line 119, in lookup
    record = self.query(word, args.query_timeout, args.verbose)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/zdict/dictionaries/yahoo.py", line 106, in query
    content['pronounce'].append(m.group(1, 2))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by wdv4758h** [comment]
The original result of "運作" from Yahoo! dictionary has space in the pronunciation, so `str.split` won't work fine.
I change to use non-greedy regex pattern and iterate over each match.
(I just notice that it won't get empty matches in the new commit after I push it, we can remove empty matches checking latter ...)
![zdict-issue-51](https://cloud.githubusercontent.com/assets/2716047/10571059/b5cb4ef6-766d-11e5-8ba0-5297dc479c40.png)

**Comment by M157q** [comment]
I don't exactly know what you mean `(I just notice that it won't get empty matches in the new commit after I push it, we can remove empty matches checking latter ...)`

**Comment by wdv4758h** [comment]
````python
for m in re.finditer('(\w+)(\[.*?\])', pronu_value):
    if m:
        content['pronounce'].append(m.group(1, 2))
````

`m` will always has data in this case.

**Comment by M157q** [comment]
so just remove `if m:`?

**Comment by wdv4758h** [comment]
yep

**Comment by M157q** [comment]
done
